name: Common Commit Actions
on: 
  workflow_call:
    inputs:
      python_version:
        description: 'Python Version passed from the caller workflow'
        default: "3.9"
        required: true
        type: string
jobs:
  truffle_hog_scan:
    name: TruffleHog Credentials Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified --since-commit ${{ env.GITHUB_SHA }}
  flake8_linting:
    name: Python flake8 Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: flake8 Lint
        uses: py-actions/flake8@v2

